PLUGIN_NAME=		go-certdist-opnsense
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		Update the certificates on OPNsense from a remote go-certdist installation
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
